version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt  # Install dependencies from your requirements.txt file
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --maxfail=1 --disable-warnings -q  # Run pytest with useful options
      - store_test_results:
          path: test_results  # Store the test results so CircleCI can display them

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Deploy (example step)
          command: |
            echo "Deploying the application..."
            # Add your deployment commands here, like uploading to AWS, GCP, or running Docker containers
            # Example: aws s3 cp your_file s3://your-bucket-name

workflows:
  version: 2
  build_and_test:
    jobs:
      - test  # Run the tests first
      - deploy:
          requires:
            - test  # Deploy only if tests pass
